### ISSUE TITLE
Namespace your plugin?

### ISSUE THREAD

**Issue by plainspace** [sebj/Sketch-Plugins#1]

**Comment by plainspace** [comment]
Maybe namespace them by what they do? Let people pick and choose in Sketch Toolbox?

**Comment by sebj** [comment]
I guess I'll break up the repo into 4 other small ones then.. pick & choose in Sketch Toolbox and all. :)

**Comment by sebj** [comment]
All done! This repo just houses some submodules/links to the other plugin repos now.

**Comment by plainspace** [comment]
:+1:

**Comment by sebj** [comment]
:smiley:
